### ISSUE TITLE
Press enter to convert

### ISSUE THREAD

**Issue by forteller** [Centipede5/youtubemp4#3]
Thanks for a useful service!

It would be easier to use if you could just press enter after pasting the URL, instead of having to reach for the mouse and click the convert buttton.

Thanks :)

**Comment by Centipede5** [comment]
Hey,

Sorry for the late reply, I didn't see this for some reason lol.

I have just updated it so you can use the enter key to start the conversion

Please let me know if you have any other ideas to make this better
